const testRequest = `<?xml version="1.0" encoding="utf-8"?>
<consulta_dnp xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.catastro.meh.es/">
  <control>
    <cudnp>1</cudnp>
    <cucons>4</cucons>
    <cucul>0</cucul>
  </control>
  <bico>
    <bi>
      <idbi>
        <cn>UR</cn>
        <rc>
          <pc1>6228817</pc1>
          <pc2>VK2662N</pc2>
          <car>0001</car>
          <cc1>O</cc1>
          <cc2>D</cc2>
        </rc>
      </idbi>
      <dt>
        <loine>
          <cp>28</cp>
          <cm>92</cm>
        </loine>
        <cmc>92</cmc>
        <np>MADRID</np>
        <nm>MOSTOLES</nm>
        <locs>
          <lous>
            <lourb>
              <dir>
                <cv>921</cv>
                <tv>CL</tv>
                <nv>CAMBRAY</nv>
                <pnp>7</pnp>
              </dir>
              <loint>
                <es>T</es>
                <pt>OD</pt>
                <pu>OS</pu>
              </loint>
              <dp>28938</dp>
              <dm>4</dm>
            </lourb>
          </lous>
        </locs>
      </dt>
      <ldt>CL CAMBRAY 7 28938 MOSTOLES (MADRID)</ldt>
      <debi>
        <luso>Residencial</luso>
        <sfc>204</sfc>
        <cpt>100,000000</cpt>
        <ant>1998</ant>
      </debi>
    </bi>
    <lcons>
      <cons>
        <lcd>VIVIENDA</lcd>
        <dt>
          <lourb>
            <loint>
              <es>1</es>
              <pt>00</pt>
              <pu>01</pu>
            </loint>
          </lourb>
        </dt>
        <dfcons>
          <stl>56</stl>
        </dfcons>
      </cons>
      <cons>
        <lcd>VIVIENDA</lcd>
        <dt>
          <lourb>
            <loint>
              <es>1</es>
              <pt>01</pt>
              <pu>01</pu>
            </loint>
          </lourb>
        </dt>
        <dfcons>
          <stl>60</stl>
        </dfcons>
      </cons>
      <cons>
        <lcd>VIVIENDA</lcd>
        <dt>
          <lourb>
            <loint>
              <es>1</es>
              <pt>02</pt>
              <pu>01</pu>
            </loint>
          </lourb>
        </dt>
        <dfcons>
          <stl>24</stl>
        </dfcons>
      </cons>
      <cons>
        <lcd>APARCAMIENTO</lcd>
        <dt>
          <lourb>
            <loint>
              <es>1</es>
              <pt>SM</pt>
              <pu>01</pu>
            </loint>
          </lourb>
        </dt>
        <dfcons>
          <stl>64</stl>
        </dfcons>
      </cons>
    </lcons>
  </bico>
</consulta_dnp>`;


describe('Start',()=>{

  test('Void test',()=>{
    expect(2+2).toBe(4);
  })
})
